### ISSUE TITLE
长远发展向建议：将网站发展为pwa应用

### ISSUE THREAD

**Issue by swift-lee** [vtbmusic/vtb-music#3]
这样基本只用吃几个H5前端就好了，不需要耗费额外的资源（愿意自己造轮子的大佬除外）。像pc和mac（一个缺轻量化应用，一个什么应用都缺）这样的生态苦手平台，发展pwa可以让用户叩头谢拜（我带头）。如果有能man愿意，还能打包上架各大平台的应用商店，即使不愿意的话各大浏览器都推出了封装pwa为本地应用的功能，也可以得到良好的用户体验

**Comment by swift-lee** [comment]
其实现在我就用新edge把网页封装成应用来使用了。总的来说只有不适配pwa应用返回键这一个问题，其他从用户体验讲都属于可用的水准了

**Comment by Dishone** [comment]
您好 目前正在构建新的前端 到时候会考虑转为PWA应用 感谢您的支持
