### ISSUE TITLE
网站卡顿问题

### ISSUE THREAD

**Issue by NriotHrreion** [vtbmusic/vtb-music#6]
进网站之后浏览器有明显卡顿与掉帧，cpu占用率提高至6.3%（其他网站最多只有1.5%），风扇狂转，这个问题能解决一下吗

[https://vtbmusic.com/](http://vtbmusic.com/)

**配置**

- CPU: i7
- 浏览器: Microsoft Edge
- 系统: win10

**Comment by KCKT0112** [comment]
我们使用了大量的即时渲染动画和即使渲染模糊的设计，在目前除非改掉设计剔除这部分之外没有任何降低的办法，有考虑过设计简洁模式，但目前开发进度很紧，并没有时间去做这个，预计在正式上线后才逐渐完善

**Comment by NriotHrreion** [comment]
好的，谢谢！
